  # Configuraciones globales
  spring:
    profiles:
      active: dev

  server:
    servlet:
      context-path: /api

  jwt:
    secret:
      key: LLAVE_SECRETA

  springdoc:
    swagger-ui:
      path: /swagger-ui.html

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

---
  # Configuraciones para el perfil dev
  spring:
    config:
      activate:
        on-profile: dev

    datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/concesionario_coches
      username: postgres
      password: 12345

---
  # Configuraciones para el perfil prod
  spring:
    config:
      activate:
        on-profile: prod

    cloud:
      azure:
        keyvault:
          secret:
            property-source-enabled: true
            property-sources[0]:
              endpoint: https://keys-springboot-psql.vault.azure.net/
              profile:
                tenant-id: f0647ab4-1320-4aef-a592-6b6b5876fcf4
              credential:
                client-id: 1a657991-5c33-48ea-9783-22263cdaaf01
                client-secret: NiI8Q~vcLiLDquyi~bPcWWCUJLv_stM1MOLpjc0l

    datasource:
      url: ${spring-datasource-url}
      username: ${spring-datasource-username}
      password: ${spring-datasource-password}
